# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Alex Kautz
email: alex.goodheart.kautz@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  My name is Alex Kautz.
  I'm a software developer currently living in Rochester New York, looking for full time employment around the globe.
  Use the links at the top of the page to learn more about my experience, read my resume, and check out my blog.
  Have fun!
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username:  alexkautz

header:
  pages:
    - name: Home
      slug: /     # <-- index.md
    - name: Experience # <-- experience.md
    - name: Resume # <- resume.md
    - name: Blog  # <-- blog.md

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: alex.goodheart.kautz@gmail.com
      link: mailto:alex.goodheart.kautz@gmail.com
  follow:
    - name: Twitter
      link: https://twitter.com/AlexKautz4
      username: "@AlexKautz4"
    # - name: Facebook
    #   link: https://www.facebook.com/alex.kautz.353
    - name: LinkedIn
      link: https://www.linkedin.com/in/alex-kautz-144002134/
    - name: GitHub
      link: https://github.com/AlexKautz

# Build settings
# theme: minima
remote_theme: eliottvincent/bay
theme: bay_jekyll_theme
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
