name: Test build

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test Site Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Zola Build
        uses: shalzz/zola-deploy-action@v0.19.2
        env:
          BUILD_ONLY: true
